#Service configuration
spring: 
  application: 
    name: gambit-discovery-service

#Server configuration
server:
  port: 8761
 
#Eureka configuration
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false